from weasyprint import HTML

def generate_resume_version_pdf(
    version_name: str,
    match_score: float,
    missing_skills: list[str],
    improved_bullets: list[dict],
) -> bytes:
    score_color = (
        "#16A34A" if match_score >= 75
        else "#D97706" if match_score >= 50
        else "#DC2626"
    )
    score_bg = (
        "#F0FDF4" if match_score >= 75
        else "#FFFBEB" if match_score >= 50
        else "#FEF2F2"
    )

    missing_pills = "".join(
        f'<span style="display:inline-block;padding:3px 10px;background:#FEF2F2;'
        f'color:#DC2626;border:1px solid #FECACA;border-radius:4px;'
        f'font-size:12px;margin:3px 4px 3px 0;">{s}</span>'
        for s in missing_skills
    ) if missing_skills else '<span style="color:#6B7280;font-size:13px;">None</span>'

    bullets_html = ""
    for b in improved_bullets:
        bullets_html += f"""
        <div style="border:1px solid #E5E7EB;border-radius:8px;
                    overflow:hidden;margin-bottom:12px;">
            <div style="background:#F9FAFB;padding:10px 14px;
                        border-bottom:1px solid #E5E7EB;">
                <p style="font-size:10px;font-weight:600;color:#9CA3AF;
                           text-transform:uppercase;letter-spacing:0.06em;
                           margin:0 0 4px;">Original</p>
                <p style="font-size:13px;color:#6B7280;
                           line-height:1.55;margin:0;
                           text-decoration:line-through;">{b['original']}</p>
            </div>
            <div style="padding:10px 14px;background:#fff;">
                <p style="font-size:10px;font-weight:600;color:#2563EB;
                           text-transform:uppercase;letter-spacing:0.06em;
                           margin:0 0 4px;">Improved</p>
                <p style="font-size:13px;color:#111827;
                           font-weight:500;line-height:1.55;margin:0;">{b['improved']}</p>
            </div>
        </div>"""

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8"/>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&display=swap');
      * {{ box-sizing: border-box; margin: 0; padding: 0; }}
      body {{ font-family: 'DM Sans', sans-serif; background: #fff;
              color: #111827; padding: 40px 48px; font-size: 14px; }}
      h1 {{ font-size: 20px; font-weight: 600; color: #111827; margin-bottom: 4px; }}
      .meta {{ font-size: 12px; color: #9CA3AF; margin-bottom: 28px; }}
      .section-label {{ font-size: 10px; font-weight: 600; color: #9CA3AF;
                        text-transform: uppercase; letter-spacing: 0.07em;
                        margin-bottom: 10px; }}
      .section {{ margin-bottom: 24px; }}
      .score-badge {{ display: inline-block; padding: 6px 18px;
                      background: {score_bg}; color: {score_color};
                      border-radius: 20px; font-size: 15px; font-weight: 700;
                      border: 1px solid {score_color}40; }}
      .divider {{ height: 1px; background: #F1F2F4; margin: 20px 0; }}
      .footer {{ margin-top: 32px; font-size: 11px; color: #9CA3AF;
                 text-align: center; border-top: 1px solid #F1F2F4;
                 padding-top: 16px; }}
    </style>
    </head>
    <body>
      <h1>{version_name}</h1>
      <p class="meta">Generated by AI Job Assistant · Tailored Resume Analysis</p>
      <div class="divider"></div>

      <div class="section">
        <p class="section-label">Match Score</p>
        <span class="score-badge">{match_score}% Match</span>
      </div>

      <div class="section">
        <p class="section-label">Missing Skills</p>
        <div>{missing_pills}</div>
      </div>

      <div class="divider"></div>

      <div class="section">
        <p class="section-label">Improved Bullet Points</p>
        {bullets_html}
      </div>

      <div class="footer">AI Job Assistant — This is an AI-generated analysis report.</div>
    </body>
    </html>"""

    return HTML(string=html).write_pdf()


def generate_cover_letter_pdf(
    company: str,
    role: str,
    content: str,
    tone: str,
) -> bytes:
    paragraphs = "".join(
        f'<p style="margin-bottom:14px;line-height:1.75;'
        f'font-size:13.5px;color:#374151;">{p.strip()}</p>'
        for p in content.strip().split("\n")
        if p.strip()
    )

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8"/>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&display=swap');
      * {{ box-sizing: border-box; margin: 0; padding: 0; }}
      body {{ font-family: 'DM Sans', sans-serif; background: #fff;
              color: #111827; padding: 48px 56px; font-size: 14px; }}
      .header {{ margin-bottom: 32px; }}
      h1 {{ font-size: 18px; font-weight: 600; color: #111827; margin-bottom: 4px; }}
      .meta {{ font-size: 12px; color: #9CA3AF; }}
      .tone-badge {{ display:inline-block; padding: 2px 10px;
                     background: #EFF6FF; color: #1D4ED8;
                     border-radius: 20px; font-size: 11px;
                     font-weight: 500; margin-top: 6px; }}
      .divider {{ height: 1px; background: #F1F2F4; margin: 24px 0; }}
      .footer {{ margin-top: 32px; font-size: 11px; color: #9CA3AF;
                 text-align: center; border-top: 1px solid #F1F2F4;
                 padding-top: 16px; }}
    </style>
    </head>
    <body>
      <div class="header">
        <h1>Cover Letter — {role} at {company}</h1>
        <p class="meta">Generated by AI Job Assistant</p>
        <span class="tone-badge">{tone.capitalize()} tone</span>
      </div>
      <div class="divider"></div>
      <div>{paragraphs}</div>
      <div class="footer">AI Job Assistant — AI-generated cover letter.</div>
    </body>
    </html>"""

    return HTML(string=html).write_pdf()